dashboard/urls.py
from django.urls import path, include

from .views import PrinterState, PrinterPrintState, PullerState

app_name = 'dashboard'
urlpatterns = [
    path("htmx/printer/state", PrinterState.as_view(), name='printer_state'),
    path("htmx/printer/printing/state", PrinterPrintState.as_view(), name='printer_print_state'),
    path("htmx/puller/state", PullerState.as_view(), name='puller_state'),
]

escpos_printer_server/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = []

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += [
    path("api/puller/", include('puller.urls', namespace="puller")),
    path("", include('dashboard.urls', namespace="dashboard")),
    path("", admin.site.urls)
]

puller/urls.py
from django.urls import path, include

from .views import PullerView

app_name = 'puller'
urlpatterns = [
    path("refresh", PullerView.as_view(), name='refresh')
]

dashboard/views.py
from django.views.generic import TemplateView
from django.core.cache import cache

import printer.models

class IndexView(TemplateView):
    template_name = "dashboard/index.html"


class PrinterState(TemplateView):
    template_name = "dashboard/htmx/printer_state.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'printer_state' in cache:
            context.update(cache.get('printer_state'))
        return context


class PullerState(TemplateView):
    template_name = "dashboard/htmx/puller_state.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'last_external_server' in cache:
            context['last_external_server'] = cache.get('last_external_server')
        else:
            context['last_external_server'] = "xx"
        return context


class PrinterPrintState(TemplateView):
    template_name = "dashboard/htmx/printing_state.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['printing_ready'] = printer.models.PrintingOrder.objects.filter(
            state=printer.models.PrintingOrderStates.READY).count()
        context['printing_finished'] = printer.models.PrintingOrder.objects.filter(
            state=printer.models.PrintingOrderStates.FINISHED).count()
        context['printing_failed'] = printer.models.PrintingOrder.objects.filter(
            state=printer.models.PrintingOrderStates.FAILED).count()
        return context

dashboard/templates/dashboard/index.html
{% extends "admin/index.html" %}
{% load i18n %}
{% load static %}

{% block sidebar %}{% endblock %}

{% block nav-sidebar %}{% include "admin/nav_sidebar.html" %} {% endblock %}

{% block extrahead %}
  {{ block.super }}
  <script src="{% static 'js/htmx.min.js' %}"></script>
{% endblock %}


{% block nav-breadcrumbs %}
  <nav aria-label="{% translate 'Breadcrumbs' %}">
    {% block breadcrumbs %}
      <div class="breadcrumbs">
        <a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
        {% if title %} &rsaquo; {{ title }}{% endif %}
      </div>
    {% endblock %}
  </nav>
{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ app_label }}{% endblock %}


{% block content %}
  <div>
    <h3> {% translate "Printer state" %} </h3>
    <div hx-get="{% url 'dashboard:printer_state' %}" hx-trigger="load, every 2s">
      Loading ...
    </div>
  </div>
  <div>
    <h3> {% translate "Printings" %} </h3>
    <div hx-get="{% url 'dashboard:printer_print_state' %}" hx-trigger="load, every 2s">
      Loading ...
    </div>
  </div>
  <div>
    <h3> {% translate "Pull from external servers" %} </h3>
    <div hx-get="{% url 'dashboard:puller_state' %}" hx-trigger="load, every 2s">
      Loading ...
    </div>
  </div>
{% endblock %}